In [ ]:
import pandas as pd

In [ ]:
race = pd.read_csv('Race_Category.csv')

In [ ]:
race.columns = ['Code','Value']
#,'White','Asian','Pacific Islander','Black','Hispanic','Native','Other']

In [ ]:
race.head()

      Code                                       Value
0     name                                       label
1      for                Census API FIPS 'for' clause
2       in                 Census API FIPS 'in' clause
3    ucgid  Uniform Census Geography Identifier clause
4  P4_003N                     Not Hispanic or Latino:

In [ ]:
sample = pd.read_csv('Final.csv')

In [ ]:
sample.head()

,Unnamed: 0,Unnamed: 0.1,FIPS,race,lon,lat,State Code,County Code,Tract Code,Block Code,COMMAREA
0,0,0,170010101001000,P1_003N,-91.270792,40.108938,17,1,10100,1000,1
1,1,1,170010101001000,P1_003N,-91.277444,40.103354,17,1,10100,1000,1
2,2,0,170010101001002,P1_003N,-91.293551,40.104785,17,1,10100,1002,1
3,3,1,170010101001002,P1_003N,-91.282438,40.100537,17,1,10100,1002,1
4,4,2,170010101001002,P1_003N,-91.291336,40.100509,17,1,10100,1002,1

In [ ]:
merged = sample.merge(race,how='left',left_on='race',right_on='Code')

In [ ]:
merged.head(20)

,Unnamed: 0,Unnamed: 0.1,FIPS,race,lon,lat,State Code,County Code,Tract Code,Block Code,COMMAREA,Code,Value
0,0,0,170010101001000,P1_003N,-91.270792,40.108938,17,1,10100,1000,1,P1_003N,White alone
1,1,1,170010101001000,P1_003N,-91.277444,40.103354,17,1,10100,1000,1,P1_003N,White alone
2,2,0,170010101001002,P1_003N,-91.293551,40.104785,17,1,10100,1002,1,P1_003N,White alone
3,3,1,170010101001002,P1_003N,-91.282438,40.100537,17,1,10100,1002,1,P1_003N,White alone
4,4,2,170010101001002,P1_003N,-91.291336,40.100509,17,1,10100,1002,1,P1_003N,White alone
5,5,3,170010101001002,P1_003N,-91.283219,40.100968,17,1,10100,1002,1,P1_003N,White alone
6,6,0,170010101001003,P1_003N,-91.288413,40.092046,17,1,10100,1003,1,P1_003N,White alone
7,7,1,170010101001003,P1_003N,-91.289248,40.090733,17,1,10100,1003,1,P1_003N,White alone
8,8,2,170010101001003,P1_003N,-91.293301,40.088580,17,1,10100,1003,1,P1_003N,White alone
9,9,3,170010101001003,P1_003N,-91.293372,40.092413,17,1,10100,1003,1,P1_003N,White alone
10,10,4,170010101001003,P1_003N,-91.290832,40.093483,17,1,10100,1003,1,P1_003N,White alone
11,11,5,170010101001003,P1_003N,-91.294418,40.093143,17,1,10100,1003,1,P1_003N,White alone
12,12,6,170010101001003,P1_003N,-91.287410,40.091826,17,1,10100,1003,1,P1_003N,White alone
13,13,7,170010101001003,P1_003N,-91.288019,40.088275,17,1,10100,1003,1,P1_003N,White alone
14,14,8,170010101001003,P1_003N,-91.292176,40.090886,17,1,10100,1003,1,P1_003N,White alone
15,15,9,170010101001003,P1_003N,-91.286717,40.093769,17,1,10100,1003,1,P1_003N,White alone
16,16,10,170010101001003,P1_003N,-91.293829,40.090860,17,1,10100,1003,1,P1_003N,White alone
17,17,11,170010101001003,P1_003N,-91.285965,40.089906,17,1,10100,1003,1,P1_003N,White alone
18,18,12,170010101001003,P1_003N,-91.281662,40.095279,17,1,10100,1003,1,P1_003N,White alone
19,19,13,170010101001003,P1_003N,-91.294497,40.093134,17,1,10100,1003,1,P1_003N,White alone

In [ ]:
merged['White'] = merged.Value.apply(lambda x : 1 if ('White' in str(x)) else 0)

In [ ]:
merged.head()

,Unnamed: 0,Unnamed: 0.1,FIPS,race,lon,lat,State Code,County Code,Tract Code,Block Code,COMMAREA,Code,Value,White
0,0,0,170010101001000,P1_003N,-91.270792,40.108938,17,1,10100,1000,1,P1_003N,White alone,1
1,1,1,170010101001000,P1_003N,-91.277444,40.103354,17,1,10100,1000,1,P1_003N,White alone,1
2,2,0,170010101001002,P1_003N,-91.293551,40.104785,17,1,10100,1002,1,P1_003N,White alone,1
3,3,1,170010101001002,P1_003N,-91.282438,40.100537,17,1,10100,1002,1,P1_003N,White alone,1
4,4,2,170010101001002,P1_003N,-91.291336,40.100509,17,1,10100,1002,1,P1_003N,White alone,1

In [ ]:
merged['Asian'] = merged.Value.apply(lambda x : 1 if ('Asian' in str(x)) else 0)
merged['Black'] = merged.Value.apply(lambda x : 1 if ('Black' in str(x)) else 0)
merged['Hispanic'] = merged.Value.apply(lambda x : 1 if ('Hispanic' in str(x)) else 0)
merged['Pacific Islander'] = merged.Value.apply(lambda x : 1 if ('Pacific' in str(x)) else 0)
merged['Native'] = merged.Value.apply(lambda x : 1 if ('Alaska' in str(x)) else 0)
merged['Other'] = merged.Value.apply(lambda x : 1 if ('Some Other Race' in str(x)) else 0)

In [ ]:
merged.head(5)

,Unnamed: 0,Unnamed: 0.1,FIPS,race,lon,lat,State Code,County Code,Tract Code,Block Code,COMMAREA,Code,Value,White,Asian,Black,Hispanic,Pacific Islander,Native,Other
0,0,0,170010101001000,P1_003N,-91.270792,40.108938,17,1,10100,1000,1,P1_003N,White alone,1,0,0,0,0,0,0
1,1,1,170010101001000,P1_003N,-91.277444,40.103354,17,1,10100,1000,1,P1_003N,White alone,1,0,0,0,0,0,0
2,2,0,170010101001002,P1_003N,-91.293551,40.104785,17,1,10100,1002,1,P1_003N,White alone,1,0,0,0,0,0,0
3,3,1,170010101001002,P1_003N,-91.282438,40.100537,17,1,10100,1002,1,P1_003N,White alone,1,0,0,0,0,0,0
4,4,2,170010101001002,P1_003N,-91.291336,40.100509,17,1,10100,1002,1,P1_003N,White alone,1,0,0,0,0,0,0

In [ ]:
hospitals = pd.read_csv('Hospitals_Processed.csv')
hospitals.head(5)

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Fax,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,NaN,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,312-746-4637,NaN,NaN,NaN,NaN,NaN,41.902212,-87.748845,"(41.902212, -87.748845)",25
1,1,Englewood MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,641 W. 63rd St,Chicago,IL,60621,312-747-7496,...,NaN,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68
2,2,Englewood STI Specialty Clinic,STI Specialty Clinic,NaN,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...","641 W. 63rd St., Lower Level",Chicago,IL,60621,312-747-8900,...,312-747-0292,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68
3,3,Greater Grand/MID-South MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4314 S. Cottage Grove,Chicago,IL,60653,312-747-0036,...,NaN,NaN,NaN,NaN,NaN,NaN,41.816326,-87.606847,"(41.816326, -87.606847)",38
4,4,Alivio Medical Center,WIC Clinic,106.0,"Mon, Tues, Thurs & Fri: 8:00 a.m. - 4:30 p.m.;...",2355 S. Western Ave.,Chicago,IL,60608,773-843-4220,...,773-650-1232,NaN,NaN,NaN,NaN,Y,41.848583,-87.685394,"(41.848583, -87.685394)",31

In [ ]:
test = pd.DataFrame(hospitals.iloc[0])

In [ ]:
test = test.transpose()
test

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Fax,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,NaN,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,312-746-4637,NaN,NaN,NaN,NaN,NaN,41.902212,-87.748845,"(41.902212, -87.748845)",25

In [ ]:
test

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Fax,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,NaN,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,312-746-4637,NaN,NaN,NaN,NaN,NaN,41.902212,-87.748845,"(41.902212, -87.748845)",25

In [ ]:
import geopy.distance

In [ ]:
merged.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'FIPS', 'race', 'lon', 'lat',
       'State Code', 'County Code', 'Tract Code', 'Block Code', 'COMMAREA',
       'Code', 'Value', 'White', 'Asian', 'Black', 'Hispanic',
       'Pacific Islander', 'Native', 'Other'],
      dtype='object')

In [ ]:
testdf = merged[merged['COMMAREA']==2]
testdf

,Unnamed: 0,Unnamed: 0.1,FIPS,race,lon,lat,State Code,County Code,Tract Code,Block Code,COMMAREA,Code,Value,White,Asian,Black,Hispanic,Pacific Islander,Native,Other
215029,215029,0,170310201001000,P1_004N,-87.688071,42.016413,17,31,20100,1000,2,P1_004N,Black or African American alone,0,0,1,0,0,0,0
215030,215030,1,170310201001000,P1_004N,-87.687745,42.015681,17,31,20100,1000,2,P1_004N,Black or African American alone,0,0,1,0,0,0,0
215031,215031,2,170310201001000,P1_003N,-87.687921,42.016645,17,31,20100,1000,2,P1_003N,White alone,1,0,0,0,0,0,0
215032,215032,3,170310201001000,P1_004N,-87.687815,42.016516,17,31,20100,1000,2,P1_004N,Black or African American alone,0,0,1,0,0,0,0
215033,215033,4,170310201001000,P1_003N,-87.688183,42.016054,17,31,20100,1000,2,P1_003N,White alone,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354982,354982,86,170310209022010,P1_003N,-87.679688,41.993074,17,31,20902,2010,2,P1_003N,White alone,1,0,0,0,0,0,0
354983,354983,87,170310209022010,P1_003N,-87.679779,41.991892,17,31,20902,2010,2,P1_003N,White alone,1,0,0,0,0,0,0
354984,354984,88,170310209022010,P1_003N,-87.679742,41.992241,17,31,20902,2010,2,P1_003N,White alone,1,0,0,0,0,0,0
354985,354985,89,170310209022010,P1_003N,-87.679572,41.992649,17,31,20902,2010,2,P1_003N,White alone,1,0,0,0,0,0,0
354986,354986,90,170310209022010,P1_008N,-87.679683,41.993021,17,31,20902,2010,2,P1_008N,Some Other Race alone,0,0,0,0,0,0,1

In [ ]:
def fun(test):
  def f(x):
    cord1 = (float(x['lat']),float(x['lon']))
    cord2 = (float(test.Latitude),float(test.Longitude))
    distance = geopy.distance.geodesic(cord1, cord2).miles
    distances.append(distance)
    races.append(x[13:20])

  distances = []
  races = []
  testdf.apply(f,axis = 1)
  racedf = pd.DataFrame(races)
  racedf['Distance'] = distances
  means = []
  means.append(racedf[racedf['White']!=0]['Distance'].mean())
  means.append(racedf[racedf['Asian']!=0]['Distance'].mean())
  means.append(racedf[racedf['Black']!=0]['Distance'].mean())
  means.append(racedf[racedf['Hispanic']!=0]['Distance'].mean())
  means.append(racedf[racedf['Pacific Islander']!=0]['Distance'].mean())
  means.append(racedf[racedf['Native']!=0]['Distance'].mean())
  means.append(racedf[racedf['Other']!=0]['Distance'].mean())
  return means

In [ ]:
hospitals

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Fax,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,NaN,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,312-746-4637,NaN,NaN,NaN,NaN,NaN,41.902212,-87.748845,"(41.902212, -87.748845)",25
1,1,Englewood MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,641 W. 63rd St,Chicago,IL,60621,312-747-7496,...,NaN,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68
2,2,Englewood STI Specialty Clinic,STI Specialty Clinic,NaN,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...","641 W. 63rd St., Lower Level",Chicago,IL,60621,312-747-8900,...,312-747-0292,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68
3,3,Greater Grand/MID-South MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4314 S. Cottage Grove,Chicago,IL,60653,312-747-0036,...,NaN,NaN,NaN,NaN,NaN,NaN,41.816326,-87.606847,"(41.816326, -87.606847)",38
4,4,Alivio Medical Center,WIC Clinic,106.0,"Mon, Tues, Thurs & Fri: 8:00 a.m. - 4:30 p.m.;...",2355 S. Western Ave.,Chicago,IL,60608,773-843-4220,...,773-650-1232,NaN,NaN,NaN,NaN,Y,41.848583,-87.685394,"(41.848583, -87.685394)",31
5,5,Englewood NHC,WIC Clinic,28.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",641 W. 63rd St.,Chicago,IL,60621,312-747-4814,...,312-745-7654,Y,Y,Y,NaN,Y,41.779692,-87.641428,"(41.779692, -87.641428)",68
6,6,Lakeview STI Specialty Clinic,STI Specialty Clinic,NaN,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues &T...","2861 N. Clark, 2nd Floor",Chicago,IL,60657,312-744-5507,...,312-744-2573,NaN,NaN,NaN,NaN,NaN,41.934367,-87.645982,"(41.934367, -87.645982)",6
7,7,Erie Health Center,WIC Clinic,NaN,"Mon, Tues, Thurs & Fri: 8:30 a.m. - 5:00 p.m.;...",1701 W. Superior St.,Chicago,IL,60610,312-432-7372,...,312-666-6228,NaN,NaN,NaN,NaN,Y,41.895006,-87.669813,"(41.895006, -87.669813)",24
8,8,Greater Lawn Health Center,WIC Clinic,5.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4150 W. 55th St.,Chicago,IL,60632,312-747-5415,...,312-745-1435,NaN,Y,NaN,NaN,Y,41.793275,-87.727664,"(41.793275, -87.727664)",62
9,9,"Asian Human Services Family Health Center, Inc.",WIC Clinic,NaN,"Mon, Wed, Thurs & Fri: 9:00 a.m. - 5:00 p.m.; ...",2424 W. Peterson Ave.,Chicago,IL,60659,773-761-2324,...,773-761-0009,NaN,NaN,NaN,NaN,Y,41.990601,-87.690739,"(41.990601, -87.690739)",2
10,10,Roseland STI Specialty Clinic,STI Specialty Clinic,NaN,Mon: 8:00 a.m. - 4:00 p.m.; Thurs: 9:00 a.m. -...,200 E. 115th St.,Chicago,IL,60628,312-747-2831,...,312-747-2841,NaN,NaN,NaN,NaN,NaN,41.685486,-87.617990,"(41.685486, -87.61799)",49
11,11,Lower West Side NHC,WIC Clinic,17.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,1713 S. Ashland Ave.,Chicago,IL,60608,312-743-0600,...,312-743-0599,NaN,Y,NaN,NaN,Y,41.858282,-87.666013,"(41.858282, -87.666013)",31
12,12,Erie Health Center,WIC Clinic,12.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",2418 W. Division St.,Chicago,IL,60622,312-744-8118,...,312-742-3415,NaN,NaN,NaN,NaN,Y,41.903118,-87.687780,"(41.903118, -87.68778)",24
13,13,Austin Clinic,WIC Clinic,19.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4909 W. Division St.,Chicago,IL,60651,312-746-4797,...,312-746-4799,NaN,NaN,NaN,NaN,Y,41.902212,-87.748845,"(41.902212, -87.748845)",25
14,14,Friend Family Health Center Inc.,WIC Clinic,23.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,800 E. 55th St.,Chicago,IL,60615,773-702-3719,...,773-702-9377,NaN,NaN,NaN,NaN,Y,41.795075,-87.606097,"(41.795075, -87.606097)",41
15,15,Chicago Family Health Center,WIC Clinic,33.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,9119 S. Exchange Ave.,Chicago,IL,60617,"773-768-0373 ext. 1180, 1181, 1182",...,773-768-5264,NaN,Y,NaN,Y,Y,41.729457,-87.552478,"(41.729457, -87.552478)",46
16,16,Lawndale MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,1201 S. Campbell St,Chicago,IL,60608,312-746-5905,...,NaN,NaN,NaN,NaN,NaN,NaN,41.866456,-87.689014,"(41.866456, -87.689014)",28
17,17,Greater Lawn MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4150 W. 55th Street,Chicago,IL,60632,312-747-1020,...,NaN,NaN,NaN,NaN,NaN,NaN,41.793275,-87.727664,"(41.793275, -87.727664)",62
18,18,Henry Booth House,WIC Clinic,103.0,Mon - Fri: 9:00 a.m. - 5:00 p.m.; Sat: 9:00 a....,2907 S. Wabash,Chicago,IL,60616,312-225-1982,...,312-265-0643,NaN,NaN,NaN,NaN,Y,41.841693,-87.625083,"(41.841693, -87.625083)",35
19,19,Westside Health Partnership,WIC Clinic,121.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,2400 S. Kedzie Ave.,Chicago,IL,60623,773-542-0288,...,773-522-2161,NaN,NaN,NaN,NaN,Y,41.848050,-87.705295,"(41.84805, -87.705295)",30
20,20,North River MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,5801 N. Pulaski Road,Chicago,IL,60646,312-744-1906,...,NaN,NaN,NaN,NaN,NaN,NaN,41.985932,-87.728369,"(41.985932, -87.728369)",13
21,21,WIC Main Office,WIC Clinic,NaN,Mon - Fri: 8:00 a.m. - 4:00 p.m.,"333 S. State St., 2nd Floor",Chicago,IL,60604,312-747-9140,...,312-747-8799,NaN,NaN,NaN,NaN,Y,41.877397,-87.627515,"(41.877397, -87.627515)",32
22,22,Alivio Medical Center - Morgan,WIC Clinic,NaN,Mon - Fri: 8:30 a.m. – 2:00 p.m.,966 W. 21st St.,Chicago,IL,60608,312-829-6838,...,312-949-7625,NaN,NaN,NaN,NaN,Y,41.854150,-87.653223,"(41.85415, -87.653223)",31
23,23,Uptown NHC,WIC Clinic,1.0,"Mon, Wed & Fri :8:00 a.m. - 4:00 p.m.; Tues & ...",845 W. Wilson Ave.,Chicago,IL,60640,312-744-0073,...,312-742-1733,Y,Y,NaN,NaN,Y,41.965367,-87.651760,"(41.965367, -87.65176)",3

In [ ]:
temp = hospitals[hospitals['Comm_Area']==2]
temp

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Fax,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area
9,9,"Asian Human Services Family Health Center, Inc.",WIC Clinic,NaN,"Mon, Wed, Thurs & Fri: 9:00 a.m. - 5:00 p.m.; ...",2424 W. Peterson Ave.,Chicago,IL,60659,773-761-2324,...,773-761-0009,NaN,NaN,NaN,NaN,Y,41.990601,-87.690739,"(41.990601, -87.690739)",2

In [ ]:
temp['distances'] = temp.apply(fun,axis = 1)
temp[['white','asian','black','hispanic','Pacific Islander','native','other']] = pd.DataFrame(temp.distances.tolist(), index= temp.index)

<ipython-input-34-0c88800c7f18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['distances'] = temp.apply(fun,axis = 1)
/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [ ]:
hospitals.fillna(-1)

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Location,Comm_Area,distances,white,asian,black,hispanic,Pacific Islander,native,other
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,-1.0,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,"(41.902212, -87.748845)",25,"[223.14097030645863, nan, 223.10279176607511, ...",223.140970,-1.0,223.102792,-1.0,-1.0,223.206190,223.056786
1,1,Englewood MHC,Mental Health Clinic,-1.0,Mon - Fri: 8:30 a.m. – 4:30 p.m.,641 W. 63rd St,Chicago,IL,60621,312-747-7496,...,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n...",223.441873,-1.0,223.401238,-1.0,-1.0,223.511387,223.349977
2,2,Englewood STI Specialty Clinic,STI Specialty Clinic,-1.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...","641 W. 63rd St., Lower Level",Chicago,IL,60621,312-747-8900,...,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n...",223.441873,-1.0,223.401238,-1.0,-1.0,223.511387,223.349977
3,3,Greater Grand/MID-South MHC,Mental Health Clinic,-1.0,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4314 S. Cottage Grove,Chicago,IL,60653,312-747-0036,...,"(41.816326, -87.606847)",38,"[226.2608415473222, nan, 226.22051039915195, n...",226.260842,-1.0,226.220510,-1.0,-1.0,226.329823,226.169904
4,4,Alivio Medical Center,WIC Clinic,106.0,"Mon, Tues, Thurs & Fri: 8:00 a.m. - 4:30 p.m.;...",2355 S. Western Ave.,Chicago,IL,60608,773-843-4220,...,"(41.848583, -87.685394)",31,"[223.9356209108853, nan, 223.8962482682285, na...",223.935621,-1.0,223.896248,-1.0,-1.0,224.002927,223.847698
5,5,Englewood NHC,WIC Clinic,28.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",641 W. 63rd St.,Chicago,IL,60621,312-747-4814,...,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n...",223.441873,-1.0,223.401238,-1.0,-1.0,223.511387,223.349977
6,6,Lakeview STI Specialty Clinic,STI Specialty Clinic,-1.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues &T...","2861 N. Clark, 2nd Floor",Chicago,IL,60657,312-744-5507,...,"(41.934367, -87.645982)",6,"[228.80155398092356, nan, 228.7631317735114, n...",228.801554,-1.0,228.763132,-1.0,-1.0,228.867199,228.716610
7,7,Erie Health Center,WIC Clinic,-1.0,"Mon, Tues, Thurs & Fri: 8:30 a.m. - 5:00 p.m.;...",1701 W. Superior St.,Chicago,IL,60610,312-432-7372,...,"(41.895006, -87.669813)",24,"[226.30992838655627, nan, 226.27111167247622, ...",226.309928,-1.0,226.271112,-1.0,-1.0,226.376263,226.223749
8,8,Greater Lawn Health Center,WIC Clinic,5.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4150 W. 55th St.,Chicago,IL,60632,312-747-5415,...,"(41.793275, -87.727664)",62,"[220.08700545791189, nan, 220.04711469160932, ...",220.087005,-1.0,220.047115,-1.0,-1.0,220.155218,219.997453
9,9,"Asian Human Services Family Health Center, Inc.",WIC Clinic,-1.0,"Mon, Wed, Thurs & Fri: 9:00 a.m. - 5:00 p.m.; ...",2424 W. Peterson Ave.,Chicago,IL,60659,773-761-2324,...,"(41.990601, -87.690739)",2,"[228.9923084412808, nan, 228.954977086271, nan...",228.992308,-1.0,228.954977,-1.0,-1.0,229.056048,228.910769
10,10,Roseland STI Specialty Clinic,STI Specialty Clinic,-1.0,Mon: 8:00 a.m. - 4:00 p.m.; Thurs: 9:00 a.m. -...,200 E. 115th St.,Chicago,IL,60628,312-747-2831,...,"(41.685486, -87.61799)",49,"[221.3056233844514, nan, 221.26350238962243, n...",221.305623,-1.0,221.263502,-1.0,-1.0,221.377735,221.209025
11,11,Lower West Side NHC,WIC Clinic,17.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,1713 S. Ashland Ave.,Chicago,IL,60608,312-743-0600,...,"(41.858282, -87.666013)",31,"[225.13813081446088, nan, 225.09876935796316, ...",225.138131,-1.0,225.098769,-1.0,-1.0,225.205417,225.050243
12,12,Erie Health Center,WIC Clinic,12.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",2418 W. Division St.,Chicago,IL,60622,312-744-8118,...,"(41.903118, -87.68778)",24,"[225.8258308380644, nan, 225.78724879988752, n...",225.825831,-1.0,225.787249,-1.0,-1.0,225.891755,225.740386
13,13,Austin Clinic,WIC Clinic,19.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4909 W. Division St.,Chicago,IL,60651,312-746-4797,...,"(41.902212, -87.748845)",25,"[223.14097030645863, nan, 223.10279176607511, ...",223.140970,-1.0,223.102792,-1.0,-1.0,223.206190,223.056786
14,14,Friend Family Health Center Inc.,WIC Clinic,23.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,800 E. 55th St.,Chicago,IL,60615,773-702-3719,...,"(41.795075, -87.606097)",41,"[225.55314891385234, nan, 225.5125135294967, n...",225.553149,-1.0,225.512514,-1.0,-1.0,225.622662,225.461252
15,15,Chicago Family Health Center,WIC Clinic,33.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,9119 S. Exchange Ave.,Chicago,IL,60617,"773-768-0373 ext. 1180, 1181, 1182",...,"(41.729457, -87.552478)",46,"[225.73469292158268, nan, 225.6928139911101, n...",225.734693,-1.0,225.692814,-1.0,-1.0,225.806381,225.638863
16,16,Lawndale MHC,Mental Health Clinic,-1.0,Mon - Fri: 8:30 a.m. – 4:30 p.m.,1201 S. Campbell St,Chicago,IL,60608,312-746-5905,...,"(41.866456, -87.689014)",28,"[224.42557550107784, nan, 224.38648130201818, ...",224.425576,-1.0,224.386481,-1.0,-1.0,224.492395,224.338526
17,17,Greater Lawn MHC,Mental Health Clinic,-1.0,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4150 W. 55th Street,Chicago,IL,60632,312-747-1020,...,"(41.793275, -87.727664)",62,"[220.08700545791189, nan, 220.04711469160932, ...",220.087005,-1.0,220.047115,-1.0,-1.0,220.155218,219.997453
18,18,Henry Booth House,WIC Clinic,103.0,Mon - Fri: 9:00 a.m. - 5:00 p.m.; Sat: 9:00 a....,2907 S. Wabash,Chicago,IL,60616,312-225-1982,...,"(41.841693, -87.625083)",35,"[226.34776592853603, nan, 226.3079066562527, n...",226.347766,-1.0,226.307907,-1.0,-1.0,226.415922,226.258314
19,19,Westside Health Partnership,WIC Clinic,121.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,2400 S. Kedzie Ave.,Chicago,IL,60623,773-542-0288,...,"(41.84805, -87.705295)",30,"[223.04217848954886, nan, 223.00292935014193, ...",223.042178,-1.0,223.002929,-1.0,-1.0,223.109269,222.954643
20,20,North River MHC,Mental Health Clinic,-1.0,Mon - Fri: 8:30 a.m. – 4:30 p.m.,5801 N. Pulaski Road,Chicago,IL,60646,312-744-1906,...,"(41.985932, -87.728369)",13,"[227.2032559396668, nan, 227.1661230659736, na...",227.203256,-1.0,227.166123,-1.0,-1.0,227.266649,227.122334
21,21,WIC Main Office,WIC Clinic,-1.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,"333 S. State St., 2nd Floor",Chicago,IL,60604,312-747-9140,...,"(41.877397, -87.627515)",32,"[227.5209181452522, nan, 227.4815766757484, na...",227.520918,-1.0,227.481577,-1.0,-1.0,227.588169,227.433094
22,22,Alivio Medical Center - Morgan,WIC Clinic,-1.0,Mon - Fri: 8:30 a.m. – 2:00 p.m.,966 W. 21st St.,Chicago,IL,60608,312-829-6838,...,"(41.85415, -87.653223)",31,"[225.55177387050114, nan, 225.51227079907162, ...",225.551774,-1.0,225.512271,-1.0,-1.0,225.619308,225.463441
23,23,Uptown NHC,WIC Clinic,1.0,"Mon, Wed & Fri :8:00 a.m. - 4:00 p.m.; Tues & ...",845 W. Wilson Ave.,Chicago,IL,60640,312-744-0073,...,"(41.965367, -87.65176)",3,"[229.71033455008205, nan, 229.67238370112906, ...",229.710335,-1.0,229.672384,-1.0,-1.0,229.775156,229.626864

In [ ]:
hospitals = hospitals.drop(['white','asian','black','hispanic','Pacific Islander','native','other'],axis = 1)

In [ ]:
hospitals

,Unnamed: 0,Site Name,Clinic Type,Site Number,Hours of Operation,Street Address,City,State,ZIP,Phone 1,...,Public Health Nursing,Family Case Management,Healthy Start Program,Healthy Families Program,WIC,Latitude,Longitude,Location,Comm_Area,distances
0,0,Austin STI Specialty Clinic,STI Specialty Clinic,NaN,Mon and Wed: 8:00 a.m. - 4:00 p.m.; Tues: 9:00...,"4909 W. Division St., Suite 411",Chicago,IL,60651,312-746-4871,...,NaN,NaN,NaN,NaN,NaN,41.902212,-87.748845,"(41.902212, -87.748845)",25,"[223.14097030645863, nan, 223.10279176607511, ..."
1,1,Englewood MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,641 W. 63rd St,Chicago,IL,60621,312-747-7496,...,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n..."
2,2,Englewood STI Specialty Clinic,STI Specialty Clinic,NaN,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...","641 W. 63rd St., Lower Level",Chicago,IL,60621,312-747-8900,...,NaN,NaN,NaN,NaN,NaN,41.779692,-87.641428,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n..."
3,3,Greater Grand/MID-South MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4314 S. Cottage Grove,Chicago,IL,60653,312-747-0036,...,NaN,NaN,NaN,NaN,NaN,41.816326,-87.606847,"(41.816326, -87.606847)",38,"[226.2608415473222, nan, 226.22051039915195, n..."
4,4,Alivio Medical Center,WIC Clinic,106.0,"Mon, Tues, Thurs & Fri: 8:00 a.m. - 4:30 p.m.;...",2355 S. Western Ave.,Chicago,IL,60608,773-843-4220,...,NaN,NaN,NaN,NaN,Y,41.848583,-87.685394,"(41.848583, -87.685394)",31,"[223.9356209108853, nan, 223.8962482682285, na..."
5,5,Englewood NHC,WIC Clinic,28.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",641 W. 63rd St.,Chicago,IL,60621,312-747-4814,...,Y,Y,Y,NaN,Y,41.779692,-87.641428,"(41.779692, -87.641428)",68,"[223.4418733518898, nan, 223.40123815751065, n..."
6,6,Lakeview STI Specialty Clinic,STI Specialty Clinic,NaN,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues &T...","2861 N. Clark, 2nd Floor",Chicago,IL,60657,312-744-5507,...,NaN,NaN,NaN,NaN,NaN,41.934367,-87.645982,"(41.934367, -87.645982)",6,"[228.80155398092356, nan, 228.7631317735114, n..."
7,7,Erie Health Center,WIC Clinic,NaN,"Mon, Tues, Thurs & Fri: 8:30 a.m. - 5:00 p.m.;...",1701 W. Superior St.,Chicago,IL,60610,312-432-7372,...,NaN,NaN,NaN,NaN,Y,41.895006,-87.669813,"(41.895006, -87.669813)",24,"[226.30992838655627, nan, 226.27111167247622, ..."
8,8,Greater Lawn Health Center,WIC Clinic,5.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4150 W. 55th St.,Chicago,IL,60632,312-747-5415,...,NaN,Y,NaN,NaN,Y,41.793275,-87.727664,"(41.793275, -87.727664)",62,"[220.08700545791189, nan, 220.04711469160932, ..."
9,9,"Asian Human Services Family Health Center, Inc.",WIC Clinic,NaN,"Mon, Wed, Thurs & Fri: 9:00 a.m. - 5:00 p.m.; ...",2424 W. Peterson Ave.,Chicago,IL,60659,773-761-2324,...,NaN,NaN,NaN,NaN,Y,41.990601,-87.690739,"(41.990601, -87.690739)",2,"[228.9923084412808, nan, 228.954977086271, nan..."
10,10,Roseland STI Specialty Clinic,STI Specialty Clinic,NaN,Mon: 8:00 a.m. - 4:00 p.m.; Thurs: 9:00 a.m. -...,200 E. 115th St.,Chicago,IL,60628,312-747-2831,...,NaN,NaN,NaN,NaN,NaN,41.685486,-87.617990,"(41.685486, -87.61799)",49,"[221.3056233844514, nan, 221.26350238962243, n..."
11,11,Lower West Side NHC,WIC Clinic,17.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,1713 S. Ashland Ave.,Chicago,IL,60608,312-743-0600,...,NaN,Y,NaN,NaN,Y,41.858282,-87.666013,"(41.858282, -87.666013)",31,"[225.13813081446088, nan, 225.09876935796316, ..."
12,12,Erie Health Center,WIC Clinic,12.0,"Mon, Wed & Fri: 8:00 a.m. - 4:00 p.m.; Tues & ...",2418 W. Division St.,Chicago,IL,60622,312-744-8118,...,NaN,NaN,NaN,NaN,Y,41.903118,-87.687780,"(41.903118, -87.68778)",24,"[225.8258308380644, nan, 225.78724879988752, n..."
13,13,Austin Clinic,WIC Clinic,19.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,4909 W. Division St.,Chicago,IL,60651,312-746-4797,...,NaN,NaN,NaN,NaN,Y,41.902212,-87.748845,"(41.902212, -87.748845)",25,"[223.14097030645863, nan, 223.10279176607511, ..."
14,14,Friend Family Health Center Inc.,WIC Clinic,23.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,800 E. 55th St.,Chicago,IL,60615,773-702-3719,...,NaN,NaN,NaN,NaN,Y,41.795075,-87.606097,"(41.795075, -87.606097)",41,"[225.55314891385234, nan, 225.5125135294967, n..."
15,15,Chicago Family Health Center,WIC Clinic,33.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,9119 S. Exchange Ave.,Chicago,IL,60617,"773-768-0373 ext. 1180, 1181, 1182",...,NaN,Y,NaN,Y,Y,41.729457,-87.552478,"(41.729457, -87.552478)",46,"[225.73469292158268, nan, 225.6928139911101, n..."
16,16,Lawndale MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,1201 S. Campbell St,Chicago,IL,60608,312-746-5905,...,NaN,NaN,NaN,NaN,NaN,41.866456,-87.689014,"(41.866456, -87.689014)",28,"[224.42557550107784, nan, 224.38648130201818, ..."
17,17,Greater Lawn MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,4150 W. 55th Street,Chicago,IL,60632,312-747-1020,...,NaN,NaN,NaN,NaN,NaN,41.793275,-87.727664,"(41.793275, -87.727664)",62,"[220.08700545791189, nan, 220.04711469160932, ..."
18,18,Henry Booth House,WIC Clinic,103.0,Mon - Fri: 9:00 a.m. - 5:00 p.m.; Sat: 9:00 a....,2907 S. Wabash,Chicago,IL,60616,312-225-1982,...,NaN,NaN,NaN,NaN,Y,41.841693,-87.625083,"(41.841693, -87.625083)",35,"[226.34776592853603, nan, 226.3079066562527, n..."
19,19,Westside Health Partnership,WIC Clinic,121.0,Mon - Fri: 8:00 a.m. - 4:00 p.m.,2400 S. Kedzie Ave.,Chicago,IL,60623,773-542-0288,...,NaN,NaN,NaN,NaN,Y,41.848050,-87.705295,"(41.84805, -87.705295)",30,"[223.04217848954886, nan, 223.00292935014193, ..."
20,20,North River MHC,Mental Health Clinic,NaN,Mon - Fri: 8:30 a.m. – 4:30 p.m.,5801 N. Pulaski Road,Chicago,IL,60646,312-744-1906,...,NaN,NaN,NaN,NaN,NaN,41.985932,-87.728369,"(41.985932, -87.728369)",13,"[227.2032559396668, nan, 227.1661230659736, na..."
21,21,WIC Main Office,WIC Clinic,NaN,Mon - Fri: 8:00 a.m. - 4:00 p.m.,"333 S. State St., 2nd Floor",Chicago,IL,60604,312-747-9140,...,NaN,NaN,NaN,NaN,Y,41.877397,-87.627515,"(41.877397, -87.627515)",32,"[227.5209181452522, nan, 227.4815766757484, na..."
22,22,Alivio Medical Center - Morgan,WIC Clinic,NaN,Mon - Fri: 8:30 a.m. – 2:00 p.m.,966 W. 21st St.,Chicago,IL,60608,312-829-6838,...,NaN,NaN,NaN,NaN,Y,41.854150,-87.653223,"(41.85415, -87.653223)",31,"[225.55177387050114, nan, 225.51227079907162, ..."
23,23,Uptown NHC,WIC Clinic,1.0,"Mon, Wed & Fri :8:00 a.m. - 4:00 p.m.; Tues & ...",845 W. Wilson Ave.,Chicago,IL,60640,312-744-0073,...,Y,Y,NaN,NaN,Y,41.965367,-87.651760,"(41.965367, -87.65176)",3,"[229.71033455008205, nan, 229.67238370112906, ..."